apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx1
        image: nginx
        resources:
          limits:
            memory: 500Mi
            cpu: "200m"
          requests:
            memory: 200Mi
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx1
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx1
