apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-nginx-deployment
  namespace: resource-quota
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: nginx-port
          containerPort: 80
