apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: apache
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: apache
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-apache
spec:
  selector:
    matchLabels:
      app: apache 
  serviceName: web-svc
  #podManagementPolicy {OrderedReady | Parallel  }
  replicas: 4
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache # Pod template's label selector
    spec:
#      terminationGracePeriodSeconds: 10
      containers:
      - name: apache-container
        image: httpd:2.4
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /var/www/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
