apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: metrics
      department: devops
  replicas: 11 
  template:
    metadata:
      labels:
        app: metrics
        department: devops
    spec:
      containers:
      - name: hello
        image: "gcr.io/google-samples/hello-app:2.0"
