apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-nginx
  name: multi-container
spec:
  volumes:
  - name: storage
    emptyDir: {}

  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: storage
      mountPath: /mnt

  - image: tomcat
    name: tomcat
    volumeMounts:
    - name: storage
      mountPath: /mnt
